levels=2
level.1.name=Prison
level.1.map=/difficulty/easy/maze.txt
level.1.npcs=/difficulty/easy/npcs.properties
level.2.name=Courtyard
level.2.map=/levels/courtyard.txt
level.2.npcs=/difficulty/easy/courtyard-npcs.properties
