levels=3
level.1.name=Hard - Cell Block
level.1.map=/campaigns/hard/map-1.txt
level.1.npcs=/campaigns/hard/npcs-1.properties
level.2.name=Hard - Tunnels
level.2.map=/campaigns/hard/map-2.txt
level.2.npcs=/campaigns/hard/npcs-2.properties
level.3.name=Hard - Outer Walls
level.3.map=/campaigns/hard/map-3.txt
level.3.npcs=/campaigns/hard/npcs-3.properties
