levels=2
level.1.name=Easy - Garden
level.1.map=/campaigns/easy/map-1.txt
level.1.npcs=/campaigns/easy/npcs-1.properties
level.2.name=Easy - Walkway
level.2.map=/campaigns/easy/map-2.txt
level.2.npcs=/campaigns/easy/npcs-2.properties
