levels=2
level.1.name=Normal - Prison
level.1.map=/maze.txt
level.1.npcs=/npcs.properties
level.2.name=Normal - Courtyard
level.2.map=/levels/courtyard.txt
level.2.npcs=/levels/courtyard-npcs.properties
